server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaspringboot?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret: bjhEGV930JVMkvQPDm4d2wKu5ifCq95fvRPzVUIAoWfvOCcF5XfSWjHYsH2rnZo+NbrDswQstTaA5uVzr3cmqg==
  expiration: 86400000